spring:
  application:
    name: ALOMilkTea
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/billyshop2?useUnicode=true&character_set_server=utf8mb4&connectionCollation=utf8mb4_unicode_ci&useSSL=true&serverTimezone=UTC&requireSSL=true
    username: root
    password: duy301104
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mandatory-file-encoding: UTF-8
  mail:
    default-encoding: UTF-8

server:
  port: 8888
  ssl:
    enabled: true
    key-store: classpath:bilishop.jks
    key-store-password: BilishopTLS@2025
    key-password: BilishopTLS@2025
    key-store-type: JKS
    key-alias: bilishop
  servlet:
    session:
      cookie:
        same-site: strict
  server-header: disabled
  error:
    include-stacktrace: never
    include-exception: false
    include-message: never
    include-binding-errors: never


storage:
  location: C:\\uploads

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 84638206
    secretKey: T7JUCGS4PBZMMDYXQ7NJ8Q4698P8E25U
    returnUrl: https://localhost:8888/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other

api:
  prefix: /api/v1
  name: api
  port: 8888